const REFERENDUMS = [
  {
    id: "eagle-mountain-r62-2026",
    county: "Utah County",
    city: "Eagle Mountain",
    title: "Eagle Mountain's Second Tax Referendum",
    subtitle: "Sponsors say the city won't hand over signature-gathering materials, and drafted a ballot pamphlet with a date state law may not allow.",
    resolution: "Resolution R-62-2026",
    filedDate: "2026-08-24",
    referableDate: "2026-09-14",
    lastUpdated: "2026-09-17",
    tags: ["property tax", "referability determination", "election date dispute", "Utah County"],
    status: "confirmed",
    keyFigure: "69.81% rate increase / $2,132,876 at stake",
    summary: "Referendum against a 69.81% property-tax increase (Resolution R-62-2026). City Attorney found it legally referable Sept. 14, 2026, but sponsors say the city hasn't provided the required petition, signature sheets, or an accurate pamphlet — whose draft cites an August 2027 election date that Utah Code appears to disallow for a tax measure without a declared disaster and unanimous council vote.",
    link: "eagle-mountain-tax-referendum-2.html"
  },
  {
    id: "eagle-mountain-finance-history",
    county: "Utah County",
    city: "Eagle Mountain",
    title: "Eagle Mountain's Balanced Budget: Where 16 Years of \"No Tax Increase\" Money Actually Went",
    subtitle: "The city's audited financial statements show a fast-growing share of city-wide property tax diverted to redevelopment project areas before it ever reaches the General Fund.",
    resolution: "N/A — finance history, companion to R-62-2026",
    filedDate: "N/A",
    referableDate: "N/A",
    lastUpdated: "2026-09-17",
    tags: ["property tax", "CRA/RDA", "tax increment financing", "Utah County", "finance history"],
    status: "confirmed",
    keyFigure: "$10.46M (FY2024) → $15.03M (FY2025) diverted to RDA Fund",
    summary: "Eagle Mountain held its certified tax rate flat for roughly 16 years — but its own ACFRs show the city's Redevelopment Agency Fund capturing a fast-growing share of city-wide property tax (34% in FY2024, 40% in FY2025) before it reaches the General Fund, via five known CRA/RDA project areas.",
    link: "eagle-mountain-finance-history.html"
  },
  {
    id: "box-elder-bear-stratos",
    county: "Box Elder County",
    city: "Brigham City area",
    title: "B.E.A.R. vs. the Stratos Data Center: The Referendum That Never Got a Signature Sheet",
    subtitle: "The county attorney ruled the MIDA project resolutions were 'administrative,' not referable — blocking the signature-gathering window before it opened. Now in court.",
    resolution: "Resolutions 26-11 & 26-12",
    filedDate: "2026-05-08",
    referableDate: "Rejected 2026-05-28 (on appeal)",
    lastUpdated: "2026-09-17",
    tags: ["MIDA", "tax increment financing", "referability determination", "Box Elder County", "data center"],
    status: "disputed",
    keyFigure: "0 signatures collected — window never opened",
    summary: "Box Elder Accountability Referendum (B.E.A.R.) tried to force a public vote on the MIDA-approved Stratos data center project. The County Attorney rejected the referendum applications as targeting 'administrative' rather than 'legislative' acts, blocking signature-gathering before it began. B.E.A.R.'s appeal is pending in 1st District Court as of Sept. 2026.",
    link: "pid-mida-referendums-blocked.html#box-elder"
  },
  {
    id: "summit-county-kimball-junction",
    county: "Summit County",
    city: "Kimball Junction",
    title: "Summit County's Referendum Against Dakota Pacific: Signatures Gathered, Then a Technicality — Then Moot",
    subtitle: "Organizers gathered 6,000+ signatures against a state-overridden rezone; a binding-format technicality disqualified enough to fall short, and the follow-on lawsuit was dismissed as moot once the Legislature approved the project by separate statute.",
    resolution: "Ordinance No. 987 (implementing S.B. 84, 2023)",
    filedDate: "2025-01-27",
    referableDate: "Declared insufficient 2025-06-23",
    lastUpdated: "2026-09-17",
    tags: ["tax increment financing", "HTRZ", "election date dispute", "Summit County", "development agreement"],
    status: "confirmed",
    keyFigure: "~3,214 of 6,000+ signatures certified — fell ~1,340 short of the 4,554 threshold",
    summary: "A citizen referendum against Summit County's Dakota Pacific/Kimball Junction rezone gathered over 6,000 signatures, but most petition packets were disqualified for failing the Election Code's binding requirements. The developer's own executives had separately formed a group urging residents not to sign. The follow-on lawsuit was dismissed as moot in Aug. 2025 after the Legislature passed S.B. 26, independently approving the same project.",
    link: "pid-mida-referendums-blocked.html#summit-county"
  },
  {
    id: "utah-referendum-law-history",
    county: "Statewide",
    city: "Utah",
    title: "The Rules Keep Changing: How Utah's Referendum Law Got Harder to Use",
    subtitle: "A bill-by-bill legislative history — the 2019 overhaul that raised land-use signature thresholds, the 2022-2023 bills that tightened petition procedure and extended two-thirds immunity, and the easing bills that died.",
    resolution: "H.B. 119 (2019), H.B. 38 (2023), S.B. 199 (2023), and related bills",
    filedDate: "N/A",
    referableDate: "N/A",
    lastUpdated: "2026-09-18",
    tags: ["referability determination", "legislative history", "statewide", "election date dispute"],
    status: "confirmed",
    keyFigure: "16% signature threshold for land-use referendums vs. 7.5% for general-law (H.B. 119, 2019)",
    summary: "Since 2019, the Utah Legislature has repeatedly rewritten local referendum law — a separate, higher signature threshold for land-use referendums, a new geographic-distribution requirement, tighter petition-packet procedure, and expanded two-thirds immunity. Every bill in this record that would have made referendums easier to use — in 2006, 2013, 2022, and 2025 — died, three of them when a chamber struck its own enacting clause. Every bill that made the process harder passed.",
    link: "utah-referendum-law-history.html"
  }
];
