const REFERENDUMS = [
  {
    id: "eagle-mountain-r62-2026",
    county: "Utah County",
    city: "Eagle Mountain",
    title: "Eagle Mountain's Second Tax Referendum",
    subtitle: "Sponsors say the city won't hand over signature-gathering materials, and drafted a ballot pamphlet with a date state law may not allow.",
    resolution: "Resolution R-62-2026",
    filedDate: "2026-08-24",
    referableDate: "2026-09-14",
    lastUpdated: "2026-10-01",
    tags: ["property tax", "referability determination", "election date dispute", "Utah County", "Nov. 3 ballot status"],
    status: "confirmed",
    keyFigure: "69.81% rate increase / $2,132,876 at stake",
    summary: "Referendum against a 69.81% property-tax increase (Resolution R-62-2026). City Attorney found it legally referable Sept. 14, 2026, but sponsors say the city hasn't provided the required petition, signature sheets, or an accurate pamphlet — whose draft cites an August 2027 election date that Utah Code appears to disallow for a tax measure without a declared disaster and unanimous council vote. Oct. 1, 2026 update: Utah County's certified Nov. 3 ballot lists one local question, Salem Prop #8; no Eagle Mountain referendum is listed.",
    link: "eagle-mountain-tax-referendum-2.html"
  },
  {
    id: "uintah-prop-9-2026",
    county: "Uintah County",
    city: "Countywide",
    title: "Uintah County Prop 9: Voters Decide Whether to Replace the Commission",
    subtitle: "A citizen petition qualified by two signatures to ask voters whether to switch from a three-member commission to a five-member district council and an appointed county manager.",
    resolution: "Proposed Optional Plan (Utah Code \u00a7\u00a7 17-62-303, -403, -404), dated April 20, 2026",
    filedDate: "2026-04-20",
    referableDate: "Petition certified 2026-07-22",
    lastUpdated: "2026-10-01",
    tags: ["citizen petition", "form of government", "on the Nov. 3 ballot", "Uintah County"],
    status: "confirmed",
    keyFigure: "2,103 signatures counted vs. 2,101 required; $560,000/yr county fiscal estimate",
    summary: "Five sponsors filed an optional plan to change Uintah County to a Council-Manager form of government. The clerk certified the petition July 22, 2026 with 2,103 signatures against a 2,101 requirement, meeting the threshold in 3 of 4 participation areas. If voters approve Proposition #9, five council members would be elected by district in 2028, the commissioner offices would end, and the new form would take effect Jan. 1, 2029. The county's fiscal statement estimates $560,000 a year, counting only manager and assistant-manager pay and benefits.",
    link: "uintah-prop-9-form-of-government.html"
  },
  {
    id: "roy-prop-10-2026",
    county: "Weber County",
    city: "Roy",
    title: "Roy Prop 10: Voters Asked to Keep or Reject a $1.75 Million Tax Increase",
    subtitle: "Residents are gathering signatures for a referendum on Roy's 34.25% property-tax increase, adopted 4-1 on Aug. 11, 2026. Weber County's certified Nov. 3 ballot already lists it as Prop #10.",
    resolution: "Resolution 26-24 (adopted Aug. 11, 2026); Ballot Proposition #10",
    filedDate: "N/A",
    referableDate: "N/A",
    lastUpdated: "2026-10-01",
    tags: ["property tax", "on the Nov. 3 ballot", "Weber County"],
    status: "confirmed",
    keyFigure: "$1,749,050 more per year (34.25%); 2025 attempt fell short, 576 of 1,743 signatures",
    summary: "Roy's council adopted a 34.25% property-tax increase 4-1 to fund employee raises. Weber County's certified ballot lists Proposition #10, a referendum on it. Signature gathering is under way as of Oct. 1, 2026; news reports say signatures are due Oct. 8. A 2025 referendum on Roy's prior increase was declared insufficient.",
    link: "roy-prop-10-tax-referendum.html"
  },
  {
    id: "eagle-mountain-finance-history",
    county: "Utah County",
    city: "Eagle Mountain",
    title: "Eagle Mountain's Balanced Budget: Where 16 Years of \"No Tax Increase\" Money Actually Went",
    subtitle: "The city's audited financial statements show a fast-growing amount of property tax going to redevelopment project areas before it ever reaches the General Fund.",
    resolution: "N/A — finance history, companion to R-62-2026",
    filedDate: "N/A",
    referableDate: "N/A",
    lastUpdated: "2026-09-17",
    tags: ["property tax", "CRA/RDA", "tax increment financing", "Utah County", "finance history"],
    status: "confirmed",
    keyFigure: "$10.46M (FY2024) → $15.03M (FY2025) to the RDA Fund",
    summary: "Eagle Mountain held its certified tax rate flat for roughly 16 years — but its own ACFRs show the city's Redevelopment Agency Fund capturing a fast-growing amount of property tax ($10.46M in FY2024, $15.03M in FY2025, equal to 34% and 40% of all city tax revenue) before it reaches the General Fund, via five known CRA/RDA project areas.",
    link: "eagle-mountain-finance-history.html"
  },
  {
    id: "box-elder-bear-stratos",
    county: "Box Elder County",
    city: "Brigham City area",
    title: "B.E.A.R. vs. the Stratos Data Center: The Referendum That Never Got a Signature Sheet",
    subtitle: "The county attorney ruled the MIDA project resolutions were 'administrative,' not referable — blocking the signature-gathering window before it opened. Now in court.",
    resolution: "Resolutions 26-11 & 26-12",
    filedDate: "2026-05-08",
    referableDate: "Rejected 2026-05-28 (on appeal)",
    lastUpdated: "2026-09-17",
    tags: ["MIDA", "tax increment financing", "referability determination", "Box Elder County", "data center"],
    status: "disputed",
    keyFigure: "0 signatures collected — window never opened",
    summary: "Box Elder Accountability Referendum (B.E.A.R.) tried to force a public vote on the MIDA-approved Stratos data center project. The County Attorney rejected the referendum applications as targeting 'administrative' rather than 'legislative' acts, blocking signature-gathering before it began. B.E.A.R.'s appeal is pending in 1st District Court as of Sept. 2026.",
    link: "pid-mida-referendums-blocked.html#box-elder"
  },
  {
    id: "summit-county-kimball-junction",
    county: "Summit County",
    city: "Kimball Junction",
    title: "Summit County's Referendum Against Dakota Pacific: Signatures Gathered, Then a Technicality — Then Moot",
    subtitle: "Organizers gathered 6,000+ signatures against a state-overridden rezone; a binding-format technicality disqualified enough to fall short, and the follow-on lawsuit was dismissed as moot once the Legislature approved the project by separate statute.",
    resolution: "Ordinance No. 987 (implementing S.B. 84, 2023)",
    filedDate: "2025-01-27",
    referableDate: "Declared insufficient 2025-06-23",
    lastUpdated: "2026-09-17",
    tags: ["tax increment financing", "HTRZ", "election date dispute", "Summit County", "development agreement"],
    status: "confirmed",
    keyFigure: "~3,214 of 6,000+ signatures certified — fell ~1,340 short of the 4,554 threshold",
    summary: "A citizen referendum against Summit County's Dakota Pacific/Kimball Junction rezone gathered over 6,000 signatures, but most petition packets were disqualified for failing the Election Code's binding requirements. The developer's own executives had separately formed a group urging residents not to sign. The follow-on lawsuit was dismissed as moot in Aug. 2025 after the Legislature passed S.B. 26, independently approving the same project.",
    link: "pid-mida-referendums-blocked.html#summit-county"
  },
  {
    id: "utah-referendum-law-history",
    county: "Statewide",
    city: "Utah",
    title: "The Rules Keep Changing: How Utah's Referendum Law Got Harder to Use",
    subtitle: "A bill-by-bill legislative history — the 2019 overhaul that raised land-use signature thresholds, the 2022-2023 bills that tightened petition procedure and extended two-thirds immunity, and the easing bills that died.",
    resolution: "H.B. 119 (2019), H.B. 38 (2023), S.B. 199 (2023), and related bills",
    filedDate: "N/A",
    referableDate: "N/A",
    lastUpdated: "2026-09-18",
    tags: ["referability determination", "legislative history", "statewide", "election date dispute"],
    status: "confirmed",
    keyFigure: "16% signature threshold for land-use referendums vs. 7.5% for general-law (H.B. 119, 2019)",
    summary: "Since 2019, the Utah Legislature has repeatedly rewritten local referendum law — a separate, higher signature threshold for land-use referendums, a new geographic-distribution requirement, tighter petition-packet procedure, and expanded two-thirds immunity. Every bill in this record that would have made referendums easier to use — in 2006, 2013, 2022, and 2025 — died, three of them when a chamber struck its own enacting clause. Every bill that made the process harder passed.",
    link: "utah-referendum-law-history.html"
  }
];
